kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "magma-oai-mme-build-config"
spec:
    runPolicy: "Serial"
    source:
        git:
            uri: "https://github.com/rdefosse/magma.git"
            ref: "oai-mme-docker-file-rh8.2"
        secrets:
        # The Secret SHALL be created from lycos (or any RHEL8 physical computer)
        - secret:
            name: etc-pki-entitlement
          destinationDir: lte/gateway/openshift/etc-pki-entitlement
        # Again these config maps SHALL be created from lycos (or any RHEL8 physical computer)
        configMaps:
          - configMap:
              name: rhsm-conf
            destinationDir: lte/gateway/openshift/rhsm-conf
          - configMap:
              name: rhsm-ca
            destinationDir: lte/gateway/openshift/rhsm-ca
    strategy:
        dockerStrategy:
            dockerfilePath: "lte/gateway/docker/mme/Dockerfile.rhel8-2.oc4-4"
    output:
        to:
            kind: "ImageStreamTag"
            name: "magma-oai-mme:ci-tmp"
