# -*- mode: ruby -*-
# vi: set ft=ruby :
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.9.1"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Mount magma directory in all VMs
  config.vm.synced_folder "../..", "/home/vagrant/magma"

  config.vm.define :magma2, primary: true do |magma2|
    # Get our prepackaged box from the atlas cloud, based on
    # - debian/contrib-jessie64
    # - linux kernel from debian jessie backports
    # - updated vbguest-tool
    magma2.vm.box = "magmacore/magma_dev"
    magma2.vm.hostname = "magma-dev2"
    magma2.vm.box_version = "1.1.20210326"

    magma2.vbguest.auto_update = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    magma2.vm.network "private_network", ip: "192.168.61.142", nic_type: "82540EM"
    # iperf3 trfserver routable IP.
    magma2.vm.network "private_network", ip: "192.168.139.1", nic_type: "82540EM"

    magma2.vm.provider "virtualbox" do |vb|
      vb.name = "magma-dev2"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.provider :libvirt do |domain, override|
      override.vm.synced_folder "../..", "/home/vagrant/magma", type: 'nfs', linux__nfs_options: ['rw','no_subtree_check','no_root_squash'], mount_options: ['nolock']
      domain.uri = "qemu+unix:///system"
      domain.memory = 6144
      domain.cpus = 4
      domain.driver = "kvm"
      domain.host = "localhost"
      domain.connect_via_ssh = false
      domain.username = $user
      domain.storage_pool_name = "default"
      domain.nic_model_type = "virtio"
      domain.management_network_name = "magma-mgmt-net"
      domain.management_network_address = "172.17.2.0/24"
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
      domain.volume_cache = "unsafe"
      domain.disk_bus = "virtio"
      domain.graphics_ip = "0.0.0.0"
    end

    magma2.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/magma_dev.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end

  config.vm.define :magma_focal2, primary: false do |magma_focal2|
    # Get our prepackaged box from the atlas cloud, based on
    # - debian/contrib-jessie64
    # - linux kernel from debian jessie backports
    # - updated vbguest-tool
    magma_focal2.vm.box = "ubuntu/focal64"
    magma_focal2.vm.hostname = "magma-dev-focal2"
    magma_focal2.vm.box_version = "20210415.0.0"
    magma_focal2.vbguest.auto_update = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    magma_focal2.vm.network "private_network", ip: "192.168.61.142", nic_type: "82540EM"
    # iperf3 trfserver routable IP.
    magma_focal2.vm.network "private_network", ip: "192.168.139.1", nic_type: "82540EM"

    magma_focal2.vm.provider "virtualbox" do |vb|
      vb.name = "magma-focal-dev2"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
    end
    magma_focal2.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/magma_dev_focal.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end

  config.vm.define :magma_trfserver2, autostart: false do |magma_trfserver2|
    magma_trfserver2.vm.box = "magmacore/magma_trfserver"
    magma_trfserver2.vm.hostname = "magma-trfserver2"
    magma_trfserver2.vm.box_version = "1.1.20210326"
    magma_trfserver2.vbguest.auto_update = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    magma_trfserver2.vm.network "private_network", ip: "192.168.61.144", nic_type: "82540EM"
    # iperf3 server IP.
    magma_trfserver2.vm.network "private_network", ip: "192.168.139.42", nic_type: "82540EM"

    magma_trfserver2.vm.provider "virtualbox" do |vb|
      vb.name = "magma-trfserver2"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "256"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.provider :libvirt do |domain, override|
      override.vm.synced_folder "../..", "/home/vagrant/magma", type: 'nfs', linux__nfs_options: ['rw','no_subtree_check','no_root_squash'], mount_options: ['nolock']
      domain.uri = "qemu+unix:///system"
      domain.memory = 6144
      domain.cpus = 4
      domain.driver = "kvm"
      domain.host = "localhost"
      domain.connect_via_ssh = false
      domain.username = $user
      domain.storage_pool_name = "default"
      domain.nic_model_type = "virtio"
      domain.management_network_name = "magma-mgmt-net"
      domain.management_network_address = "172.17.2.0/24"
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
      domain.volume_cache = "unsafe"
      domain.disk_bus = "virtio"
      domain.graphics_ip = "0.0.0.0"
    end

    magma_trfserver2.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/magma_trfserver.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end

  config.vm.define :magma_test2, autostart: false do |magma_test2|
    # Get our prepackaged box from the atlas cloud
    magma_test2.vm.box = "magmacore/magma_test"
    magma_test2.vm.hostname = "magma-test2"
    magma_test2.vm.box_version = "1.1.20210326"
    magma_test2.vbguest.auto_update = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    magma_test2.vm.network "private_network", ip: "192.168.61.141", nic_type: "82540EM"
    # UE trfgen network
    magma_test2.vm.network "private_network", ip: "192.168.138.11", nic_type: "82540EM"
    #config.ssh.private_key_path = "~/.ssh/vagrant.key"
    config.ssh.forward_agent = true

    magma_test2.vm.provider "virtualbox" do |vb|
      vb.name = "magma_test2"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.provider :libvirt do |domain, override|
      override.vm.synced_folder "../..", "/home/vagrant/magma", type: 'nfs', linux__nfs_options: ['rw','no_subtree_check','no_root_squash'], mount_options: ['nolock']
      domain.uri = "qemu+unix:///system"
      domain.memory = 1024
      domain.cpus = 1
      domain.driver = "kvm"
      domain.host = "localhost"
      domain.connect_via_ssh = false
      domain.username = $user
      domain.storage_pool_name = "default"
      domain.nic_model_type = "virtio"
      domain.management_network_name = "magma-mgmt-net"
      domain.management_network_address = "172.17.2.0/24"
      domain.nested = true
      domain.cpu_mode = "host-passthrough"
      domain.volume_cache = "unsafe"
      domain.disk_bus = "virtio"
      domain.graphics_ip = "0.0.0.0"
    end

    magma_test2.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/magma_test.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end

  config.vm.define :magma_prod2, autostart: false do |magma_prod2|
    magma_prod2.vm.synced_folder ".", "/vagrant", disabled: true
    magma_prod2.vm.synced_folder "../..", "/home/vagrant/magma", disabled: true
    # upstream box won't start due to missing linux-headers-4.9.0-9
    # using slightly customized box based on debian/stretch64
    magma_prod2.vm.box = "amarpad/magma_prod"
    magma_prod2.vm.hostname = "magma-prod"
    magma_prod2.vbguest.auto_update = false

    # magma_prod2.vm.box = "debian/stretch64"
    # magma_prod2.vm.box_version = "9.9.1"
    # Create a private network, which can be bridged to a physical eNB
    magma_prod2.vm.network "private_network", ip: "10.10.2.1", nic_type: "82540EM"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    magma_prod2.vm.network "private_network", ip: "192.168.61.151", nic_type: "82540EM"
    #config.ssh.private_key_path = "~/.ssh/vagrant.key"
    config.ssh.forward_agent = true

    magma_prod2.vm.provider "virtualbox" do |vb|
      vb.name = "magma_prod"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    magma_prod2.vm.provision "shell",
                            inline: "apt update"

    magma_prod2.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "deploy/magma_prod.yml"
      ansible.inventory_path = "deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end

  config.vm.define :ovs_build, autostart: false do |ovs_build|
    ovs_build.vm.box = "generic/debian9"
    ovs_build.vm.hostname = "build-ovs"
    ovs_build.vm.network "public_network"
    ovs_build.ssh.forward_agent = true
    ovs_build.vm.box_check_update = false

    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
    config.ssh.insert_key = false
  end

  config.vm.define :oai_hss, autostart: false do |oai_hss|
    oai_hss.vm.box = "ubuntu/bionic64"
    oai_hss.vm.hostname = "oai-hss"
    oai_hss.vm.network "public_network"
    oai_hss.ssh.forward_agent = true
    oai_hss.vm.box_check_update = false

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    oai_hss.vm.network "private_network", ip: "192.168.61.153", nic_type: "82540EM"
    config.ssh.insert_key = false
    oai_hss.vm.provider "virtualbox" do |vb|
      vb.name = "oai-hss"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

  end

end
