# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Config secrets for orc8r module
# TODO: it should be possible to range at the top level and dynamically generate secrets based on subdirectories under .secrets/configs/
{{- if .Values.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-configs-orc8r
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
{{- if .Values.secret.configs.enabled }}
{{ $thanos_enabled := .Values.thanos_enabled}}
{{- range $key, $value := .Values.secret.configs.orc8r }}
  # Set metricsd.yml explicitly if thanos is enabled
  {{- if eq $key "metricsd.yml" }}
    {{- if $thanos_enabled }}
  {{ $value = `
       profile: "prometheus"

       prometheusQueryAddress: "http://{{ .Release.name }}-thanos-query-http:10902"

       alertmanagerApiURL: "http://{{ .Release.name }}-alertmanager:9093/api/v2"
       prometheusConfigServiceURL: "http://{{ .Release.name }}-prometheus-configurer:9100/v1"
       alertmanagerConfigServiceURL: "http://{{ .Release.name }}-alertmanager-configurer:9101/v1"` }}
    {{- end }}
  {{- end }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
